version: "3"

services:
    genshin-dailynote-helper:
        container_name: genshin-dailynote-helper
        build: .
        restart: always
        volumes: 
            - ./dailynotereminder/config/config.yaml:/app/dailynotereminder/config/config.yaml
        environment:
            - TZ=Asia/Shanghai